# Generated by Django 5.1.6 on 2025-04-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(auto_now_add=True)),
                ('zakat_year', models.PositiveIntegerField()),
                ('total_zakatable_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nisab_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('zakat_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('zakat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='ZakatAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('cash', 'Cash'), ('inventory', 'Inventory'), ('receivables', 'Receivables'), ('investments', 'Investments'), ('other', 'Other Assets')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zakat_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='zakat.zakatcalculation')),
            ],
        ),
        migrations.CreateModel(
            name='ZakatLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_type', models.CharField(choices=[('payables', 'Payables'), ('loans', 'Loans'), ('other', 'Other Liabilities')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zakat_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='zakat.zakatcalculation')),
            ],
        ),
    ]
